## Esercizo 1
Si consideri il sistema lineare Ax=b, con A matrice e b termine noto memorizzati nel file ``Dati0.mat``.  Risolvere il sistema utilizzando il metodo più adatto al problema proposto e commentare i risultati ottenuti  giustificandoli alla luce della teoria. 

Per la lettura dei dati procedere nel seguente modo:

``from scipy.io import loadmat``

``import numpy as np``

``dati = loadmat('Dati0.mat')``

``A=dati["A"] ``

`` b=dati["b"] ``

In [42]:
from scipy.io import loadmat

import numpy as np
import matplotlib.pyplot as plt
import time
from scipy.linalg import lu

dati = loadmat('Dati0.mat')

A = dati["A"] 

b = dati["b"]

In [3]:
def gauss_seidel(A,b,n=50,x=None):
    """Solves the equation Ax=b via the Gauss-Seidel iterative method."""
    # Create an initial guess if needed
    if x is None:
        x = np.zeros(np.shape(b))
    
    L = np.tril(A)
    U = A-L
    for i in range(n):
        x = np.dot(np.linalg.inv(L),b-np.dot(U,x))
    return x

In [3]:
def jacobi(A,b,n=50,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = np.zeros(np.shape(b))
                                                                                                                                                                   
    D = np.diag(A)
    R = A - np.diagflat(D)
                                                                                                                                                                         
    for i in range(n):
        x = (b - np.dot(R,x)) / D
    return x


In [15]:
def sor_solver(A, b, w, tollerance, x=None):
    """Solves the equation Ax=b via Succesive Over Relaxation Method."""

    """ w: relaxation factor (typically 0 < w < 2)
        tollerance: the amount of error accepted
    """
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = np.zeros(np.shape(b))

    residual = np.linalg.norm(np.matmul(A, x) - b)
    while residual > tollerance:
        for i in range(A.shape[0]):
            sigma = 0
            for j in range(A.shape[1]):
                if j != i:
                    sigma += A[i][j] * x[j]
            x[i] = (1 - w) * x[i] + (w / A[i][i]) * (b[i] - sigma)
        residual = np.linalg.norm(np.matmul(A, x) - b)
        #print('Residual: {0:10.6g}'.format(residual))
    return x

In [5]:
#plt.spy(A)

In [4]:

'''np.count_nonzero(A)/400**2

is_defpos = np.all(np.linalg.eigvals(A))
is_sim = np.all(A == A.T)
print(is_defpos)
print(is_sim)'''
print("Calculating the result...")
n= 1300
start = time.time()
#x = sor_solver(A,b,1.8,1e-1)
#x = gauss_seidel(A,b,n)
x = jacobi(A,b,n)
end = time.time()
diff = np.linalg.solve(A,b)-x
print("Accuracy of the result:",np.linalg.norm(diff,2))
print("Time elapsed",end-start)

Calculating the result...
Accuracy of the result: 0.00015453020254512797
Time elapsed 6.481194972991943


## Esercizio 2

La sequenza 

$$x_1=1$$
$$x_n= 2^{n-1} \left( \sqrt{1+ \frac{x_{n-1}}{2^{n-2}} }-1 \right)    \quad \quad n=2,3,...,\quad (1) $$

converge a $log(2)$, cioè  $\lim_{n \rightarrow \infty} x_n= log(2)$

- Si calcolino i valori della sequenza (1) per $n=1,..,71$

- Costruire un grafico in cui nelle ascisse vi sia  il valore di $n=1,..,71$  e nelle ordinate il corrispondente valore di $x_n$ . 

- La successione converge a log(2)? In corrispondenza di quale $n$ si verifica un pessimo risultato? Spiegare alla luce della teoria

- Manipolando opportunamente la formula (1) scrivere una formula  equivalente  ma piu\' stabile per ottenere la sequenza $\tilde x_n$
algebricamente equivalente alla (1).

- Valutare la formula proposta per calcolare la sequenza $\tilde x_n $ per $n=1,..,71$

- Costruire un grafico in cui nelle ascisse vi sia  il valore di n  e nelle ordinate il corrispondente valore di $\tilde x_n$ 

- Calcolare l'errore relativo di ogni $x_n$ rispetto al valore esatto $log(2)$ 


- Calcolare l'errore relativo di ogni $\tilde x_n$ rispetto al valore esatto $log(2)$

## Esercizo 3
Si consideri il sistema lineare Ax=b, con A matrice e b termine noto memorizzati nel file ``Dati1.mat``.  Risolvere il sistema utilizzando il metodo più adatto al problema proposto e commentare i risultati ottenuti  giustificandoli alla luce della teoria. 


In [5]:
dati1 = loadmat('Dati1.mat')

A1 = dati1["A"] 

b1 = dati1["b"]

In [7]:
#plt.spy(A1)

In [31]:
def least_squares(A, b):
    """Solves the equation Ax=b via Least Squares Method."""
    n = A.shape[1]
    r = np.linalg.matrix_rank(A)
    U, sigma, VT = np.linalg.svd(A, full_matrices=True)
    D_plus = np.diag(np.hstack([1/sigma[:r], np.zeros(n-r)]))
    V = VT.T
    A_plus = V.dot(D_plus).dot(U.T)
    w = A_plus.dot(b)
    error = np.linalg.norm(A.dot(w) - b, ord=2) ** 2
    return w,error

In [45]:
''' r = np.linalg.matrix_rank(A1)
print(r)
np.shape(A1)

print(np.linalg.cond(A1))

print(np.count_nonzero(A1) / np.size(A1))
'''



#w,error = least_squares(A1,b1)
#print(w)
#print(error)

#plt.scatter(A1, b1)
#plt.plot(A1, w*A1, c='red')

A= [[ 4. -1.  0. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [ 0. -1.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  4. -1.  0.]
 [ 0.  0.  0. ... -1.  4. -1.]
 [ 0.  0.  0. ...  0. -1.  4.]]
L= [[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [-0.25        1.          0.         ...  0.          0.
   0.        ]
 [ 0.         -0.26666667  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ... -0.35578608  1.
   0.        ]
 [ 0.          0.          0.         ... -0.01589789 -0.34625126
   1.        ]]
U= [[ 4.         -1.          0.         ...  0.          0.
   0.        ]
 [ 0.          3.75       -1.         ...  0.          0.
   0.        ]
 [ 0.          0.          3.73333333 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  3.22794823 -1.14845904
  -0.05131755]
 [ 0.          0.          0.         ... 